{% set version = '1.7.15' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-indicspecies
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/indicspecies_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/indicspecies/indicspecies_{{ version }}.tar.gz
  sha256: 17bf1f6c3b4af5c373ae31e58ebeb81b6b469f0c90618c399983508637278340

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-permute
  run:
    - r-base
    - r-permute

test:
  commands:
    - $R -e "library('indicspecies')"           # [not win]
    - "\"%R%\" -e \"library('indicspecies')\""  # [win]

about:
  home: https://emf-creaf.github.io/indicspecies/
  license: GPL-2.0-or-later
  summary: Functions to assess the strength and statistical significance of the relationship
    between species occurrence/abundance and groups of sites [De Caceres & Legendre
    (2009) <doi:10.1890/08-1823.1>]. Also includes functions to measure species niche
    breadth using resource categories [De Caceres et al. (2011) <doi:10.1111/J.1600-0706.2011.19679.x>].
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - PaulineSGN

# Package: indicspecies
# Type: Package
# Title: Relationship Between Species and Groups of Sites
# Version: 1.7.15
# Date: 2024-08-21
# Authors@R: c( person('Miquel', 'De Caceres', role=c('aut','cre'), email='miquelcaceres@gmail.com', comment = c(ORCID = "0000-0001-7132-2080")), person('Florian', 'Jansen', role='aut'), person('Noah', 'Dell', role='aut'))
# Description: Functions to assess the strength and statistical significance of the relationship between species occurrence/abundance and groups of sites [De Caceres & Legendre (2009) <doi:10.1890/08-1823.1>]. Also includes functions to measure species niche breadth using resource categories [De Caceres et al. (2011) <doi:10.1111/J.1600-0706.2011.19679.x>].
# Depends: permute
# Suggests: rmarkdown, knitr, testthat (>= 3.0.0)
# Encoding: UTF-8
# License: GPL (>= 2)
# URL: https://emf-creaf.github.io/indicspecies/
# BugReports: https://github.com/emf-creaf/indicspecies/issues
# RoxygenNote: 7.3.2
# LazyLoad: yes
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-08-21 10:07:03 UTC; miquel
# Author: Miquel De Caceres [aut, cre] (<https://orcid.org/0000-0001-7132-2080>), Florian Jansen [aut], Noah Dell [aut]
# Maintainer: Miquel De Caceres <miquelcaceres@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-08-21 21:30:02 UTC
